#### Random Forest
- A collection of decision trees on a random basis (feature randomness)
- An example of ensemble learning technique, using Bagging
- In Decision Tree, we divide features in subsets of a single tree
- A versatile and powerful Machine Learning algorithm that belongs to the Ensemble Learning Family
- Known for its simplicity and running efficiently on large datasets
- Used for both classification and regression tasks
- Operates by constructing a multitude of decision trees at training time and outputting the class that is mode of the classes (classification) or mean prediction (in regression) of the individual trees
- 

- Parallel Tree Growing - Bagging
    - In Random Forest, we divide features in seperate Decision Trees (can have repititions)
    - If there is an error in one tree, the other tree might not have it

#### How does it work?
- Bagging
    - creates multiple decision trees using bagging
    - randomly selects  samples from the dataset with replacement and builds a decision tree for each sample

- Random Feature Selection
    - In each split during tree construction, a random subset of features is considered. This makes it more robust and prevents overfitting

- Aggregation of Results
    - Mode for Classification
    - Mean for Regression

#### Key Features
- Robustness
- Handling Non-Linearity
- Feature Importance - gives insights of which features are important

#### Advantages
- High Accuracy
- Versatility
- Ease of Use

#### Applications
- In finance for credit scoring etc
- In healthcare for disease prediction etc
- In e-commerce for recommendation systems etc
- For stock market predictions

#### Best Practices and Considerations
- Number of Trees 
- Depth of Trees - More trees > One tree with more depth
- Feature Selection

#### Challenges
- Model Interpretability
- Computationally Intensive

#### Practical

###### Random Forest 

Random Forest is a supervised learning algorithm, like you can see from its name, it creates a forest and somehow makes it random. The forest it builds is an ensemble of Decision Trees, most of the time trained with 'bagging' method.

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

#### Classification

In [2]:
# Load data
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
# Encode features
le = LabelEncoder()
for i in df.columns:
    if df[i].dtype == 'object' or df[i].dtype == 'category':
        df[i] = le.fit_transform(df[i])

In [4]:
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [5]:
# Split the data
X = df.drop('sex', axis=1)
y = df['sex']

# Traint test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create, train and predict the model
model = RandomForestClassifier(n_estimators=500, max_depth=10, max_features='log2',
                               criterion='entropy', random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy Score: ", accuracy_score(y_test, y_pred))
print("Classification Report: \n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy Score:  0.6530612244897959
Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.26      0.37        19
           1       0.66      0.90      0.76        30

    accuracy                           0.65        49
   macro avg       0.64      0.58      0.57        49
weighted avg       0.65      0.65      0.61        49

Confusion Matrix:
 [[ 5 14]
 [ 3 27]]

#### Regression

In [6]:
df = sns.load_dataset('tips')

In [7]:
# Encode features
le = LabelEncoder()
for i in df.columns:
    if df[i].dtype == 'object' or df[i].dtype == 'category':
        df[i] = le.fit_transform(df[i])

In [8]:
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [9]:
# Split the data
X = df.drop('tip', axis=1)
y = df['tip']

# Traint test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create, train and predict the model
model = RandomForestRegressor(n_estimators=500, random_state=42,
                              max_depth=10, min_samples_split=5, min_samples_leaf=2)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("R2 Score: ", r2_score(y_test, y_pred))
print("Mean Squared Error: ", mean_squared_error(y_test, y_pred))
print("Mean Absolute Error: ", mean_absolute_error(y_test, y_pred))

R2 Score:  0.26647745417707724
Mean Squared Error:  0.91688216339021
Mean Absolute Error:  0.7551489012451615

In [110]:
# We have a small dataset thats why our metrics are not good